### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_roberta'

### ISSUE THREAD

**Issue by Sosycs** [expertailab/ISAAQ#4]
Hello, 
I am facing this error when trying to train the ISAAQ solvers on the TQA dataset using pre-trainings and the commands:
#True/False Questions
!python tqa_tf_sc.py -r IR -s
!python tqa_tf_sc.py -r NSP -s
!python tqa_tf_sc.py -r NN -s

What is this about? 
I have tried to import the RoBERTa using: from transformers import RobertaConfig, RobertaModel, RobertaForMaskedLM
but did not solve it.

Any help please?

**Comment by rortegagit** [comment]
Hi, please take a look to the solution to #3

**Comment by Sosycs** [comment]
Thank you for your reply @rortegagit , I have and checked the version using pip show transformers and got:
Name: transformers
Version: 2.11.0
Summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
Home-page: https://github.com/huggingface/transformers
Author: Thomas Wolf, Lysandre Debut, Victor Sanh, Julien Chaumond, Sam Shleifer, Patrick von Platen, Google AI Language Team Authors, Open AI team Authors, Facebook AI Authors, Carnegie Mellon University Authors
Author-email: thomas@huggingface.co
License: Apache
Location: c:\programdata\anaconda3\envs\isaacenv\lib\site-packages
Requires: filelock, numpy, packaging, regex, requests, sacremoses, sentencepiece, tokenizers, tqdm
Required-by:

with that , I wrote 'from transformers import RobertaForSequenceClassification'
and faced the error: 
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from transformers import RobertaForSequenceClassification
ImportError: cannot import name 'RobertaForSequenceClassification' from 'transformers' (c:\ProgramData\anaconda3\envs\isaacenv\lib\site-packages\transformers\__init__.py)

and when trying to train the ISAAQ solvers:
Traceback (most recent call last):
  File "tqa_tf_sc.py", line 1, in <module>
    from transformers import RobertaForSequenceClassification, AdamW, BertConfig, BertTokenizer, BertPreTrainedModel, BertModel, BertForMultipleChoice, RobertaForMultipleChoice, RobertaTokenizer
ImportError: cannot import name 'RobertaForSequenceClassification' from 'transformers' (c:\ProgramData\anaconda3\envs\isaacenv\lib\site-packages\transformers\__init__.py)
Traceback (most recent call last):
  File "tqa_tf_sc.py", line 1, in <module>
    from transformers import RobertaForSequenceClassification, AdamW, BertConfig, BertTokenizer, BertPreTrainedModel, BertModel, BertForMultipleChoice, RobertaForMultipleChoice, RobertaTokenizer
ImportError: cannot import name 'RobertaForSequenceClassification' from 'transformers' (c:\ProgramData\anaconda3\envs\isaacenv\lib\site-packages\transformers\__init__.py)
Traceback (most recent call last):
  File "tqa_tf_sc.py", line 1, in <module>
    from transformers import RobertaForSequenceClassification, AdamW, BertConfig, BertTokenizer, BertPreTrainedModel, BertModel, BertForMultipleChoice, RobertaForMultipleChoice, RobertaTokenizer
ImportError: cannot import name 'RobertaForSequenceClassification' from 'transformers' (c:\ProgramData\anaconda3\envs\isaacenv\lib\site-packages\transformers\__init__.py)

I appreciate your help and admire your work!

**Comment by rortegagit** [comment]
Which version of torch do you have installed?

**Comment by Sosycs** [comment]
torch = 2.0.1+cu118
tensorflow =1.15.0

**Comment by rortegagit** [comment]
The transformers package is now too old, and prone to fail. However, try to install transformers 2.3.0 instead of 2.11.0.

**Comment by Sosycs** [comment]
What about Python version and Pytorch?

I am getting "RuntimeError: cublas runtime error : the GPU program failed to execute at" and upgrading pytorch alone cause many conflicts.

I appreciate your reply and cooperation!

**Comment by rortegagit** [comment]
Python 3.6.5 is the version I used to execute these experiments, but newer versions are working too. I recommend you to start again with a fresh new conda environment and the versions I have mentioned before.

**Comment by Sosycs** [comment]
> The transformers package is now too old, and prone to fail. However, try to install transformers 2.3.0 instead of 2.11.0.


Do you mean transformers 3.2.0?
and can you specify the torch version that works?

Thank you for your reply.
